version: '3'

services:
  mongodb:
    image: mongo:4.0.6
    restart: always
    container_name: "assistantbot-mongodb"
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - dbdata:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  bot:
    container_name: "assistantbot"
    logging:
      options:
        max-size: "100M"
        max-file: "10"
    restart: always
    volumes:
    - ".:/usr/src/bot"
    env_file: .env


volumes:
  dbdata:

